In [2]:
import pandas as pd
import numpy as np

In [4]:
# Leer datos de parquet 

df = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/DIATREND_balanced_age_undersampling_PH4.parquet')
df.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1,val,train,test,val,train
1,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,92.0,2015-12-04,20:45:00,1,val,train,test,val,train
2,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,106.0,2015-12-04,21:00:00,1,val,train,test,val,train
3,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,122.0,2015-12-04,21:15:00,1,val,train,test,val,train
4,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,147.0,2015-12-04,21:30:00,1,val,train,test,val,train
5,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,163.0,2015-12-04,21:45:00,1,val,train,test,val,train
6,117.0,100.0,94.0,83.0,74.0,81.0,92.0,106.0,164.0,2015-12-04,22:00:00,1,val,train,test,val,train
7,100.0,94.0,83.0,74.0,81.0,92.0,106.0,122.0,159.0,2015-12-04,22:15:00,1,val,train,test,val,train
8,94.0,83.0,74.0,81.0,92.0,106.0,122.0,147.0,215.0,2015-12-04,22:30:00,1,val,train,test,val,train
9,83.0,74.0,81.0,92.0,106.0,122.0,147.0,163.0,257.0,2015-12-04,22:45:00,1,val,train,test,val,train

In [5]:
df_fol0_over = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/balanced_outputs/windows_with_5folds_DiaTrend_2026-03-27_PH4_fold0_age_oversampling.parquet')
df_fol0_over.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,165.0,161.0,141.0,137.0,131.0,128.0,117.0,122.0,122.0,2019-06-10,17:15:00,42,train,train,train,val,test
1,226.0,220.0,215.0,211.0,203.0,194.0,176.0,164.0,180.0,2019-11-14,03:15:00,30,train,train,test,train,train
2,179.0,205.0,224.0,230.0,225.0,216.0,237.0,229.0,177.0,2019-09-27,12:45:00,30,train,train,test,train,train
3,149.0,145.0,161.0,171.0,182.0,166.0,158.0,161.0,122.0,2019-08-25,04:15:00,46,train,train,train,test,train
4,229.0,182.0,133.0,96.0,91.0,92.0,66.0,53.0,96.0,2021-08-08,20:45:00,21,train,train,train,test,train
5,192.0,202.0,190.0,173.0,153.0,137.0,126.0,126.0,149.0,2019-05-11,16:45:00,36,train,train,train,test,val
6,242.0,278.0,313.0,365.0,375.0,382.0,365.0,358.0,342.0,2020-12-25,21:00:00,18,train,test,train,train,val
7,149.0,137.0,138.0,133.0,131.0,134.0,136.0,167.0,227.0,2019-10-28,10:30:00,38,train,val,test,train,train
8,202.0,303.0,331.0,331.0,326.0,312.0,265.0,261.0,191.0,2019-09-05,13:00:00,8,train,train,train,train,test
9,244.0,253.0,267.0,258.0,269.0,254.0,257.0,285.0,244.0,2019-11-05,15:45:00,10,train,train,train,test,train

In [ ]:
df_completo_over = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/DIATREND_balanced_age_oversampling_PH4.parquet')
df_completo_over.head(10)

In [8]:
df_nuevo_over = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/balanced_outputs/windows_with_5folds_DiaTrend_2026-03-27_PH4_fold0_sex_oversampling.parquet')
df_nuevo_over.head(10)
df_test = df_nuevo_over[df_nuevo_over["split"] == 'test']
df_test.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,split
2943916,157.0,188.0,209.0,225.0,250.0,239.0,230.0,224.0,195.0,2019-10-01,14:45:00,15,test
2943917,188.0,209.0,225.0,250.0,239.0,230.0,224.0,212.0,189.0,2019-10-01,15:00:00,15,test
2943918,209.0,225.0,250.0,239.0,230.0,224.0,212.0,215.0,185.0,2019-10-01,15:15:00,15,test
2943919,225.0,250.0,239.0,230.0,224.0,212.0,215.0,212.0,189.0,2019-10-01,15:30:00,15,test
2943920,250.0,239.0,230.0,224.0,212.0,215.0,212.0,195.0,186.0,2019-10-01,15:45:00,15,test
2943921,239.0,230.0,224.0,212.0,215.0,212.0,195.0,189.0,211.0,2019-10-01,16:00:00,15,test
2943922,230.0,224.0,212.0,215.0,212.0,195.0,189.0,185.0,235.0,2019-10-01,16:15:00,15,test
2943923,224.0,212.0,215.0,212.0,195.0,189.0,185.0,189.0,239.0,2019-10-01,16:30:00,15,test
2943924,212.0,215.0,212.0,195.0,189.0,185.0,189.0,186.0,244.0,2019-10-01,16:45:00,15,test
2943925,215.0,212.0,195.0,189.0,185.0,189.0,186.0,211.0,238.0,2019-10-01,17:00:00,15,test

In [10]:
df_nuevo_over.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,split
0,255.0,247.0,227.0,234.0,255.0,320.0,328.0,279.0,206.0,2020-07-26,08:00:00,10,train
1,224.0,231.0,233.0,210.0,208.0,217.0,202.0,186.0,160.0,2019-09-14,15:15:00,2,train
2,175.0,175.0,163.0,158.0,156.0,148.0,161.0,152.0,164.0,2019-11-02,08:00:00,30,train
3,298.0,279.0,254.0,237.0,218.0,202.0,187.0,184.0,190.0,2020-11-01,10:00:00,5,train
4,248.0,249.0,234.0,222.0,219.0,206.0,202.0,195.0,120.0,2019-09-19,18:15:00,2,train
5,294.0,279.0,275.0,302.0,334.0,306.0,314.0,313.0,221.0,2018-08-29,12:00:00,3,train
6,132.0,102.0,88.0,75.0,84.0,90.0,116.0,152.0,126.0,2021-08-29,21:45:00,27,train
7,98.0,89.0,84.0,79.0,62.0,76.0,85.0,94.0,88.0,2019-12-04,09:15:00,2,train
8,247.0,244.0,241.0,238.0,230.0,225.0,234.0,242.0,239.0,2021-07-16,04:30:00,5,train
9,222.0,214.0,204.0,170.0,155.0,142.0,136.0,135.0,165.0,2022-04-10,17:15:00,41,train

In [11]:
df_nuevo_over.tail(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,split
3422849,282.0,245.0,222.0,182.0,175.0,153.0,120.0,114.0,89.0,2022-06-28,20:45:00,9,test
3422850,245.0,222.0,182.0,175.0,153.0,120.0,114.0,119.0,83.0,2022-06-28,21:00:00,9,test
3422851,222.0,182.0,175.0,153.0,120.0,114.0,119.0,108.0,83.0,2022-06-28,21:15:00,9,test
3422852,182.0,175.0,153.0,120.0,114.0,119.0,108.0,102.0,97.0,2022-06-28,21:30:00,9,test
3422853,175.0,153.0,120.0,114.0,119.0,108.0,102.0,89.0,112.0,2022-06-28,21:45:00,9,test
3422854,153.0,120.0,114.0,119.0,108.0,102.0,89.0,83.0,121.0,2022-06-28,22:00:00,9,test
3422855,120.0,114.0,119.0,108.0,102.0,89.0,83.0,83.0,120.0,2022-06-28,22:15:00,9,test
3422856,114.0,119.0,108.0,102.0,89.0,83.0,83.0,97.0,126.0,2022-06-28,22:30:00,9,test
3422857,119.0,108.0,102.0,89.0,83.0,83.0,97.0,112.0,152.0,2022-06-28,22:45:00,9,test
3422858,108.0,102.0,89.0,83.0,83.0,97.0,112.0,121.0,164.0,2022-06-28,23:00:00,9,test