In [1]:
import pandas as pd
import numpy as np

In [4]:
df_nuevo_over = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/balanced_outputs/windows_with_5folds_DiaTrend_2026-03-27_PH4_fold0_age_oversampling.parquet')
df_nuevo_over.head(10)
# df_test = df_nuevo_over[df_nuevo_over["split"] == 'test']
# df_test.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,split
0,127.0,120.0,119.0,123.0,125.0,126.0,131.0,140.0,179.0,2019-07-01,06:30:00,30,train
1,132.0,138.0,139.0,137.0,132.0,129.0,129.0,129.0,103.0,2019-01-23,19:15:00,29,train
2,208.0,208.0,212.0,245.0,266.0,267.0,274.0,274.0,148.0,2020-08-21,18:00:00,2,train
3,193.0,211.0,241.0,260.0,309.0,332.0,289.0,238.0,124.0,2022-02-20,11:00:00,10,train
4,90.0,93.0,91.0,86.0,85.0,80.0,64.0,68.0,121.0,2019-10-21,17:00:00,30,train
5,259.0,258.0,239.0,211.0,194.0,159.0,148.0,143.0,124.0,2019-02-03,18:30:00,29,train
6,271.0,260.0,255.0,241.0,224.0,213.0,205.0,200.0,193.0,2021-10-30,04:45:00,7,train
7,139.0,131.0,126.0,117.0,106.0,93.0,91.0,88.0,103.0,2019-04-24,19:30:00,29,train
8,91.0,93.0,104.0,100.0,100.0,109.0,131.0,132.0,139.0,2019-04-15,17:15:00,42,train
9,82.0,74.0,74.0,133.0,177.0,235.0,309.0,327.0,338.0,2020-01-31,16:30:00,7,train

In [6]:
print(df_nuevo_over.dtypes)

x0            float64
x1            float64
x2            float64
x3            float64
x4            float64
x5            float64
x6            float64
x7            float64
y             float64
x_date_7       object
x_time_7       object
patient_id     object
split          object
dtype: object

In [7]:
df_nuevo_smote = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/balanced_outputs/windows_with_5folds_DiaTrend_2026-03-27_PH4_fold4_age_smote.parquet')
df_nuevo_smote.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,split
0,96.158649,103.748523,149.562869,173.934178,195.185654,195.655696,184.874262,187.470042,158.059916,2019-08-21,19:15:00,37,train
1,136.070608,130.232348,125.697044,123.070608,114.232348,113.302956,104.464696,99.232348,76.323481,2019-09-21,09:15:00,38,train
2,177.270062,186.620374,189.109564,184.919751,196.240748,188.649688,179.949065,180.540125,165.000000,2019-05-07,08:30:00,39,train
3,208.783648,188.783648,187.059623,163.529811,142.470189,147.059623,148.746164,153.843270,158.783648,2019-10-05,19:00:00,46,train
4,149.863625,179.372725,157.286337,168.863625,185.000000,184.950013,175.118175,130.913612,84.813638,2019-11-19,18:30:00,37,train
5,123.000000,121.000000,143.000000,173.000000,181.000000,173.000000,164.000000,159.000000,211.000000,2021-09-27,19:45:00,1,train
6,130.000000,119.000000,108.000000,97.000000,99.000000,137.000000,185.000000,218.000000,267.000000,2021-11-05,17:30:00,26,train
7,169.794335,162.931445,160.241927,163.931445,166.068555,162.483853,172.310482,171.310482,187.620963,2019-07-12,10:15:00,30,train
8,208.631955,206.000000,191.289944,181.710056,189.078100,193.736089,211.315978,238.315978,200.657989,2019-11-09,19:30:00,38,train
9,193.000000,193.000000,191.000000,184.000000,177.000000,170.000000,157.000000,145.000000,184.000000,2020-01-16,16:15:00,5,train

### Analisis de las técnicas aplicadas sobre DIATREND

Vamos a repasar los .parquet de algunos de los folds balanceados , y iremos comparando con el conjunto original , que contiene los 5 folds, filtrando por fold y por las condiciones que establezcamos , para comprobar que , s por ejemplo, hemos hecho undersampling, entonces en el fold balanceado, las ventanas que pertenezcan a train, deben haber sido reducidad, es decir, debe haber menos que antes para ese fold y train. Si por ejemplo, hemos hecho oversampling, entonces lo que debemos observar es que para ese fold , en el conjunto de train, debe haber venatans duplicadas

In [5]:
df_diatrend_original = pd.read_parquet('C:/Users/User/Desktop/TFM-Glucose-Prediction/data/DIATREND/windows_with_5folds_DiaTrend_2026-03-27_PH4.parquet')
df_diatrend_original.head(10)

,x0,x1,x2,x3,x4,x5,x6,x7,y,x_date_7,x_time_7,patient_id,fold_0,fold_1,fold_2,fold_3,fold_4
0,160.0,162.0,167.0,150.0,164.0,147.0,130.0,137.0,143.0,2015-12-01,22:45:00,1,val,train,test,val,train
1,177.0,176.0,195.0,194.0,153.0,117.0,100.0,94.0,92.0,2015-12-04,20:45:00,1,val,train,test,val,train
2,176.0,195.0,194.0,153.0,117.0,100.0,94.0,83.0,106.0,2015-12-04,21:00:00,1,val,train,test,val,train
3,195.0,194.0,153.0,117.0,100.0,94.0,83.0,74.0,122.0,2015-12-04,21:15:00,1,val,train,test,val,train
4,194.0,153.0,117.0,100.0,94.0,83.0,74.0,81.0,147.0,2015-12-04,21:30:00,1,val,train,test,val,train
5,153.0,117.0,100.0,94.0,83.0,74.0,81.0,92.0,163.0,2015-12-04,21:45:00,1,val,train,test,val,train
6,117.0,100.0,94.0,83.0,74.0,81.0,92.0,106.0,164.0,2015-12-04,22:00:00,1,val,train,test,val,train
7,100.0,94.0,83.0,74.0,81.0,92.0,106.0,122.0,159.0,2015-12-04,22:15:00,1,val,train,test,val,train
8,94.0,83.0,74.0,81.0,92.0,106.0,122.0,147.0,215.0,2015-12-04,22:30:00,1,val,train,test,val,train
9,83.0,74.0,81.0,92.0,106.0,122.0,147.0,163.0,257.0,2015-12-04,22:45:00,1,val,train,test,val,train